import { rootPath } from "@/analyze";
import ProjectInfo from "@/components/ProjectInfo";
import { ProjectSelector } from "@/components/ProjectSelector";
import Link from "next/link";
import "tailwindcss/tailwind.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <div className="navbar bg-base-100">
          <a className="btn btn-ghost normal-case text-xl">
            DepChecker by @bjornallvin
          </a>
        </div>
        <ProjectSelector rootPath={rootPath} />
        <div className="drawer drawer-mobile">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content ">
            <label
              htmlFor="my-drawer-2"
              className="btn btn-primary drawer-button lg:hidden"
            >
              Open drawer
            </label>
            {children}
          </div>
          <div className="drawer-side">
            <label htmlFor="my-drawer-2" className="drawer-overlay"></label>

            {/* @ts-expect-error Async Server Component */}
            <ProjectInfo />
          </div>
        </div>
      </body>
    </html>
  );
}
