import Link from "next/link";
import "tailwindcss/tailwind.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={"p-4"}>
          <Link href={"/"} className={"px-4"}>
            Start
          </Link>
          <Link href={"/locked"}>Locked</Link>
        </div>
        <div className="w-full h-screen dark:bg-slate-800">
          <div className={`max-w-6xl mx-auto px-8 pt-8`}>{children}</div>
        </div>
      </body>
    </html>
  );
}
