import ProjectInfo from "@/components/ProjectInfo";
import Link from "next/link";
import "tailwindcss/tailwind.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen dark:bg-slate-800">
        <div className={"p-4"}>
          <Link href={"/"} className={"px-4"}>
            Start
          </Link>
          <Link href={"/locked"}>Locked</Link>
        </div>
        <div className="w-full h-screen  dark:bg-slate-800 dark:text-slate-300">
          <div className={`max-w-8xl px-8 pt-8 h-screen `}>
            <div className="flex items-start h-screen ">
              {/* @ts-expect-error Async Server Component */}
              <ProjectInfo />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
